---
title: "DDRL"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lfe)

wvs <- 
  read_csv("data/wvs_cleaned.csv", guess_max = 300000) %>% 
  select(-c(dem_imp, dem_political_sys)) %>% 
  mutate(age = year - birth_year) %>% 
  filter(
    !is.na(dem_overall), 
    country != "Channel Islands"
    ) %>% 
  mutate(
    ranking = 
      case_when(
      education == "No formal education"  ~ 1,
      education == "Incomplete elementary" ~ 2,
      education == "Complete elementary" ~ 3,
      education == "Incomplete secondary" ~ 4,
      education == "Complete secondary" ~ 5,
      education == "Some higher education"  ~ 6,
      education == "Higher education"  ~ 7
    ), 
    education = fct_reorder(education, ranking)
  )
```

```{r}
wvs %>% 
  summarise_all(~ sum(is.na(.))) 
```


```{r}
wvs %>% 
  ggplot(aes(dem_overall)) + 
  geom_histogram(bins = 20) + 
  labs(
    x = "Attitudes towards Democracy", 
    y = "Number", 
    title = "Histogram of Attitudes towards Democracy", 
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```



```{r, fig.height=10, fig.width=8}
###BY Country 

wvs %>% 
  filter(wave == 6) %>% 
  group_by(country, region, year) %>% 
  summarize(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(
    country = fct_reorder(country, dem_overall),
    year = as.factor(year)
    ) %>% 
  ggplot(aes(dem_overall, country)) + 
  geom_point(aes(color = region)) +
  geom_text(aes(label = year), nudge_x = 0.03, size = 3) +
  scale_color_discrete(name = "Region") + 
  labs(
    x = "Attitudes towards Democracy", 
    y = NULL, 
    title = "Attitudes towards Democracy in Wave 6 by Country", 
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```


```{r}
###BY Region

wvs %>% 
  filter(wave == 6) %>% 
  group_by(country, region) %>% 
  summarize(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  group_by(region) %>% 
  summarize(dem_overall = mean(dem_overall, na.rm = TRUE)) %>% 
  mutate(region = fct_reorder(region, dem_overall)) %>% 
  ggplot(aes(dem_overall, region)) + 
  geom_point() + 
  labs(
    x = "Attitudes towards Democracy", 
    y = NULL, 
    title = "Attitudes towards Democracy in Wave 6 by Region", 
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  ) + 
  coord_cartesian(xlim = c(0.2, 0.9))


wvs %>% 
  filter(wave == 6) %>% 
  group_by(country, region) %>% 
  summarize(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  filter(region == "Europe & Central Asia")
```

```{r}
gdp <- 
  read_xls("data/gdp_per_capita.xls") %>% 
  gather(key = year, value = gdp_pc, -country) %>% 
  mutate(year = as.integer(str_remove(year, "pc_")))


wvs %>% 
  filter(wave == 6) %>% 
  group_by(country, region, year) %>% 
  summarize(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  left_join(
    gdp, by = c("country", "year")
  ) %>% 
  ggplot(aes(gdp_pc, dem_overall, color = region)) + 
  geom_point() + 
  ggrepel::geom_text_repel(aes(label = country), size = 3) + 
  scale_color_discrete(name = NULL) + 
  scale_x_log10() + 
  labs(
    x = "GDP per Capita", 
    y = "Attitudes towards Democracy", 
    title = "Attitudes towards Democracy vs GDP per Capita in Wave 6", 
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"), 
    legend.position = "bottom"
  )

  
```





```{r}
world <- 
  wvs %>% 
  group_by(wave, country) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  group_by(wave) %>% 
  summarize(dem_overall = mean(dem_overall))


wvs %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  group_by(wave, region) %>% 
  summarise(dem_overall = mean(dem_overall, na.rm = TRUE)) %>% 
  ggplot(aes(wave, dem_overall)) + 
  geom_line(data = world, color = "gray80", size = 1) +
  geom_line() + #color = "#01babe"
  facet_wrap(vars(region)) + 
  scale_y_continuous(breaks = seq(0.2, 0.7, 0.1), minor_breaks = NULL) + 
  scale_x_continuous(minor_breaks = NULL) + 
  # theme_minimal() + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy (1994-2020) by Region",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

```

```{r}

wvs %>% 
  group_by(wave, country, region, sub_region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  filter(region == "Europe & Central Asia") %>% 
  group_by(wave, sub_region) %>% 
  summarise(dem_overall = mean(dem_overall, na.rm = TRUE)) %>% 
  ggplot(aes(wave, dem_overall, color = sub_region)) + 
  geom_line() + 
  geom_point(data = . %>% filter(wave == 3)) + 
  ggrepel::geom_text_repel(
    data = . %>% filter(wave == 3), 
    aes(label = sub_region), 
    hjust = 0, 
    nudge_x = -1, 
    nudge_y = 0
  ) + 
  coord_cartesian(xlim = c(2.4, 6)) + 
  theme_minimal() + 
  theme(legend.position = "none") +
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in Europe & Central Asia (1994-2020)",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  ) 
```



```{r}
# four_wave_countries <- 
#   wvs %>% 
#   count(wave, country) %>% 
#   count(country, sort = TRUE) %>% 
#   filter(n > 3) %>% 
#   pull(country)
# 
# 
# wvs %>% 
#   filter(country %in% four_wave_countries) %>% 
#   group_by(wave, country, region) %>% 
#   summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
#   ggplot(aes(wave, dem_overall)) + 
#   geom_line(data = world, color = "gray80", size = 1) +
#   geom_line() + 
#   facet_wrap(vars(country)) + 
#   labs(
#     x = "Wave", 
#     y = "Score", 
#     title = "Attitudes towards Democracy in select countries (1994-2020)",
#     subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
#     caption = "Source: World Values Survey"
#   ) + 
#   theme_minimal() + 
#   theme(
#     plot.title = element_text(hjust = 0.5, face = "bold")
#   ) 


```


```{r}
wvs_6 <- 
  wvs %>% 
  filter(wave == 6) 

fit_1 <- lm(dem_overall ~ education, data = wvs_6)
summary(fit_1)

fit_2 <- lm(dem_overall ~ education + gender + age + employment + income, data = wvs_6)
summary(fit_2)

fit_3 <- felm(dem_overall ~  education + gender + age + employment + income | country, data = wvs_6)
summary(fit_3)

fit_4 <- felm(dem_overall ~  education + gender + age + employment + income | country + year, data = wvs)
summary(fit_4)
```



```{r}
wvs %>% 
  count(education) %>% 
  mutate(
    ranking = 
      case_when(
      education == "No formal education"  ~ 1,
      education == "Incomplete elementary" ~ 2,
      education == "Complete elementary" ~ 3,
      education == "Incomplete secondary" ~ 4,
      education == "Complete secondary" ~ 5,
      education == "Some higher education"  ~ 6,
      education == "Higher education"  ~ 7
    ), 
    education = fct_reorder(education, ranking)
  ) %>% 
  ggplot(aes(education, n)) + 
  geom_col() + 
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) + 
  labs(
    x = NULL, 
    y = "Count", 
    title = "Respondents' Level of Education", 
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  ) 


```


```{r}
wvs %>% 
  mutate(
    ranking = 
      case_when(
      income == "Lower class"  ~ 1,
      income == "Working class" ~ 2,
      income == "Lower middle class" ~ 3,
      income == "Upper middle class" ~ 4,
      income == "Upper class" ~ 5
    ), 
    income = fct_reorder(income, ranking)
  ) %>% 
  count(education, income) %>% 
  group_by(income) %>% 
  mutate(prop = n / sum(n)) %>% 
  drop_na() %>% 
  ggplot(aes(education, income, size = prop, color = prop)) + 
  geom_point() + 
  scale_color_viridis_c(name = "proportion") + 
  theme(
    axis.text.x = element_text(angle = 20, hjust = 1)
  ) + 
  labs(
    x = NULL, 
    y = NULL, 
    title = "Income versus levels of education", 
    caption = "Source: World Values Survey"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
  

wvs %>% 
  mutate(
    ranking = 
      case_when(
      income == "Lower class"  ~ 1,
      income == "Working class" ~ 2,
      income == "Lower middle class" ~ 3,
      income == "Upper middle class" ~ 4,
      income == "Upper class" ~ 5
    ), 
    income = fct_reorder(income, ranking)
  ) %>% 
  count(education, income) %>% 
  group_by(income) %>% 
  mutate(prop = n / sum(n)) %>% 
  arrange(income)
```

```{r}
wvs %>% 
  ggplot(aes(age)) + 
  geom_histogram(bins = 20) + 
  labs(
    x = "Age", 
    y = "Count", 
    title = "Histogram of Respondents' Age"
  ) + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold")
  )

```

```{r}

wvs %>% 
  filter(region == "South Asia") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ggplot(aes(wave, dem_overall, color = country)) + 
  geom_line() + 
  geom_point(size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in South Asia (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )

  
```


```{r}

wvs %>% 
  filter(region == "North America") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(wave, dem_overall)) + 
    geom_line(
    data = world %>% mutate(wave = as.factor(wave)), 
    color = "gray80", 
    size = 1, 
    aes(group = 1)) +
  geom_line(aes(group = country, color = country)) +
  geom_point(aes(color = country, group = country), size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in North America (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )

```

```{r}

wvs %>% 
  filter(region == "Latin America & Caribbean") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(wave, dem_overall, color = country, group = country)) + 
  geom_line() + 
  geom_point(size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in Latin America (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )


```

```{r}

wvs %>% 
  filter(region == "East Asia & Pacific") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(wave, dem_overall, color = country, group = country)) + 
  geom_line() + 
  geom_point(size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in East Asia & Pacific (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )
```

```{r}

wvs %>% 
  filter(region == "Sub-Saharan Africa") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(wave, dem_overall, color = country, group = country)) + 
  geom_line() + 
  geom_point(size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in Sub-Saharan Africa (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )

```

###India 
```{r}
wvs %>% 
  filter(country == "India") %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(education, dem_overall, color = wave)) + 
  geom_count()

wvs %>% 
  filter(country == "India") %>%
  mutate(wave = as.factor(wave)) %>% 
  group_by(wave, income) %>% 
  summarize(dem_overall = mean(dem_overall)) %>% 
  ggplot(aes(dem_overall, income, color = wave)) + 
  geom_point()
```

```{r}

wvs %>% 
  filter(region == "Middle East & North Africa") %>% 
  group_by(wave, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ungroup() %>% 
  mutate(wave = as.factor(wave)) %>% 
  ggplot(aes(wave, dem_overall)) + 
  geom_line(aes(group = country, color = country)) +
  geom_point(aes(color = country, group = country), size = 2) + 
  labs(
    x = "Wave", 
    y = "Score", 
    title = "Attitudes towards Democracy in MENA (1994-2020) by Country",
    subtitle = "Higher scores indicate more pro-democratic views on a scale of -1 to 1",
    caption = "Source: World Values Survey"
  )

```

```{r}
wvs %>% 
  # filter(year %in% 2003:2012) %>% 
  group_by(year, country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  ggplot(aes(year, dem_overall)) + 
  geom_point()
```

```{r}
wvs %>% 
  filter(wave == 6) %>% 
  group_by(country, region) %>% 
  summarise(dem_overall = weighted.mean(dem_overall, w = weight, na.rm = TRUE)) %>% 
  arrange(dem_overall)
```





